version: '3.4'

services:
  spacebotv4:
    image: spacebotv4
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 src/main.py "]
    ports:
      - 5678:5678
